name: flutter_rating_stars
description: A Flutter package to create Rating Stars bar. It will be useful for your awesome app.
version: 1.0.0
homepage: https://minhhung2556.medium.com
repository: https://gitlab.com/romantic_project/flutter_story_list.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/star_off.svg